spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

jwt:
  secret: test-secret-key-for-jwt-token-generation-minimum-256-bits-required-for-testing
  expiration: 86400000
  issuer: ecommerce-test

cors:
  allowed-origins: "http://localhost:3000,http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.miempresa.ecommerce: DEBUG
    org.springframework.security: DEBUG
